Hover:
  ShowAKA: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: No
  DeducedTypes: Yes

CompileFlags:
  Add: [-Wunused-function, -Wall, -Wextra]
  Remove: -Werror

Diagnostics:
  ClangTidy:
    Add: [performance*, modernize-deprecated*, modernize-pass-by-value, modernize-raw-string-literal, readability-redundant-control-flow]
    # Add: ['*']
    #Add: modernize*
    #Remove: modernize-use-trailing-return-type
