Hover:
  ShowAKA: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: No
  DeducedTypes: Yes

CompileFlags:
  Add:
    [
      -Wunused-function,
      -Wall,
      -Wextra,
      -Wshadow,
      -Wpedantic,
      -Werror=unused-variable,
      -Wexceptions,
      -Wno-switch-enum,
      -Wimplicit-fallthrough,
    ]
  Remove: -Werror

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [
        performance*,
        modernize*,
        # modernize-deprecated*,
        # modernize-pass-by-value,
        # modernize-use-override,
        # modernize-loop-convert,
        # modernize-raw-string-literal,
        google-explicit-constructor,
        readability-simplify-boolean-expr,
        bugprone-exception-escape,
        "*redundant*",
        "*unused*",
      ]
    # Add: ['*']
    #Add: modernize*
    Remove: [modernize-use-trailing-return-type, modernize-use-using]
