Hover:
  ShowAKA: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: No
  DeducedTypes: Yes

CompileFlags:
  Add: [-Wunused-function, -Wall, -Wextra, -Wshadow, -Wpedantic]
  Remove: -Werror

Diagnostics:
  ClangTidy:
    Add: [performance*,
      modernize-deprecated*,
      modernize-pass-by-value,
      modernize-use-override,
      modernize-raw-string-literal,
      google-explicit-constructor,
      readability-redundant-control-flow]
    # Add: ['*']
    #Add: modernize*
    #Remove: modernize-use-trailing-return-type
